---
- name: Nginx | Install required system packages.
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - nginx
  tags:
    - packages
    - provision
    - webserver

- name: Nginx | Create log directory
  file: >
    dest={{ project.logs }}
    state=directory
  tags:
    - webserver

- name: Commmon | Create the SSL directory.
  when: nginx.ssl is defined
  file: >
    state=directory
    path=/etc/nginx/ssl/
  tags:
    - config
    - ssl
    - webserver

- name: Commmon | Upload SSL private key.
  when: nginx.ssl is defined
  notify: restart nginx
  copy: >
    src={{ nginx.ssl.private }}
    dest=/etc/nginx/ssl/{{ project.name }}-private
  tags:
    - config
    - ssl
    - webserver

- name: Commmon | Upload SSL public key.
  when: nginx.ssl is defined
  notify: restart nginx
  copy: >
    src={{ nginx.ssl.public }}
    dest=/etc/nginx/ssl/{{ project.name }}-public
  tags:
    - config
    - ssl
    - webserver

- name: Nginx | remove default nginx site
  notify: restart nginx
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Nginx | Install nginx configuration file.
  notify: restart nginx
  template: >
    src=vhost.conf.j2
    dest=/etc/nginx/sites-enabled/{{ project.name }}
  tags:
    - config
    - nginx
    - webserver
    - update

- name: Nginx | Allow port 80 through firewall
  ufw: >
    rule=allow
    port=80
    proto=tcp
  tags:
    - firewall

- name: Servers | Allow port 443 through firewall
  when: nginx.ssl is defined
  ufw: >
    rule=allow
    port=443
    proto=tcp
  tags:
    - firewall
